# Generated by Django 2.2.11 on 2020-03-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muscu_site', '0004_auto_20200302_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(blank=True, max_length=100)),
                ('sets', models.IntegerField(default=1)),
                ('reps', models.IntegerField(default=1)),
                ('break_time', models.IntegerField(default=60)),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='muscu_site.TrainingSession')),
            ],
        ),
        migrations.DeleteModel(
            name='Exercice',
        ),
    ]
