# Generated by Django 2.2.11 on 2020-03-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscu_site', '0005_auto_20200316_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='break_time',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
