# Generated by Django 2.2.11 on 2020-04-01 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muscu_site', '0007_auto_20200323_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='date_completed',
        ),
        migrations.CreateModel(
            name='TrainingSessionCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField(null=True)),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_completed', to='muscu_site.TrainingSession')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=800)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercise_completed', to='muscu_site.Exercise')),
                ('training_session_completed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercise_completed', to='muscu_site.TrainingSessionCompleted')),
            ],
        ),
    ]
