# Generated by Django 2.2.13 on 2021-07-07 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muscu_site', '0010_auto_20200527_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
