# Generated by Django 2.2.13 on 2021-07-07 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muscu_site', '0011_trainingsession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_session', to=settings.AUTH_USER_MODEL),
        ),
    ]
