# Generated by Django 2.2.13 on 2021-07-07 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muscu_site', '0012_auto_20210707_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsessioncompleted',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_session_completed', to=settings.AUTH_USER_MODEL),
        ),
    ]
