# Generated by Django 2.2.10 on 2020-03-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscu_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='sets',
            field=models.IntegerField(default=1),
        ),
    ]
