# Generated by Django 2.2.10 on 2020-03-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muscu_site', '0002_auto_20200302_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercice',
            old_name='label',
            new_name='exercice',
        ),
        migrations.RenameField(
            model_name='trainingsession',
            old_name='label',
            new_name='session_title',
        ),
    ]
