# Generated by Django 2.2.10 on 2020-03-02 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscu_site', '0003_auto_20200302_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
