# Generated by Django 2.2.11 on 2020-03-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscu_site', '0006_auto_20200318_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='date_completed',
            field=models.DateField(null=True),
        ),
    ]
